export const CITIES = [
  { id: 'indore', name: 'Indore', state: 'MP', lat: 22.7533, lng: 75.8937, areas: ['Vijay Nagar', 'Palasia', 'Scheme 54', 'South Tukoganj', 'AB Road', 'Bhawarkua'] },
  { id: 'bhopal', name: 'Bhopal', state: 'MP', lat: 23.2599, lng: 77.4126, areas: ['MP Nagar', 'Arera Colony', 'Gulmohar', 'Kolar Road'] },
  { id: 'mumbai', name: 'Mumbai', state: 'MH', lat: 19.0760, lng: 72.8777, areas: ['Bandra', 'Andheri West', 'Juhu', 'Colaba', 'Powai'] },
  { id: 'delhi', name: 'Delhi NCR', state: 'DL', lat: 28.6139, lng: 77.2090, areas: ['Connaught Place', 'South Extension', 'Saket', 'Gurugram', 'Noida'] },
  { id: 'bengaluru', name: 'Bengaluru', state: 'KA', lat: 12.9716, lng: 77.5946, areas: ['Koramangala', 'Indiranagar', 'HSR Layout', 'Whitefield'] },
];

export const SERVICE_CATEGORIES = [
  {
    id: 'haircut',
    name: 'Haircut',
    iconName: 'scissors',
    color: '#2563eb',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    description: 'Precision cuts, fades, layers & hair styling',
    startingPrice: 249,
  },
  {
    id: 'beard',
    name: 'Beard',
    iconName: 'beard',
    color: '#2563eb',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    description: 'Beard trim, shape, mustache styling & hot towel',
    startingPrice: 149,
  },
  {
    id: 'facial',
    name: 'Facial',
    iconName: 'sparkles',
    color: '#2563eb',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    description: 'Deep cleansing, fruit facial, gold & anti-aging',
    startingPrice: 599,
  },
  {
    id: 'hair-color',
    name: 'Hair Color',
    iconName: 'palette',
    color: '#2563eb',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    description: 'Root touchup, global hair color, balayage & highlights',
    startingPrice: 899,
  },
  {
    id: 'waxing',
    name: 'Waxing',
    iconName: 'wax',
    color: '#2563eb',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    description: 'Rica waxing, full body wax & bikini wax',
    startingPrice: 399,
  },
  {
    id: 'more',
    name: 'More',
    iconName: 'grid',
    color: '#2563eb',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    description: 'Spa, manicure, pedicure, bridal & makeup services',
    startingPrice: 499,
  },
];

export const ALL_SERVICES_EXTENDED = [
  ...SERVICE_CATEGORIES,
  {
    id: 'spa',
    name: 'Head Spa & Massage',
    iconName: 'flower',
    color: '#059669',
    bgColor: '#ecfdf5',
    borderColor: '#a7f3d0',
    description: 'Relaxing head massage, body massage & aromatherapy',
    startingPrice: 699,
  },
  {
    id: 'manicure-pedicure',
    name: 'Mani & Pedi',
    iconName: 'sparkles',
    color: '#d97706',
    bgColor: '#fffbeb',
    borderColor: '#fde68a',
    description: 'Nail art, spa manicure and luxury pedicure',
    startingPrice: 449,
  },
  {
    id: 'bridal',
    name: 'Bridal & Groom',
    iconName: 'heart',
    color: '#db2777',
    bgColor: '#fdf2f8',
    borderColor: '#fbcfe8',
    description: 'Complete pre-wedding grooming & makeup packages',
    startingPrice: 2999,
  },
];

export const INITIAL_SALONS = [
  {
    id: 'looks-salon',
    name: 'Looks Salon',
    rating: 4.7,
    reviewsCount: 1240,
    distance: '0.8 km away',
    address: 'Plot 14, Ring Road, Vijay Nagar',
    city: 'Indore',
    lat: 22.7533,
    lng: 75.8937,
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=800&q=80',
    ],
    startingPrice: 299,
    isFavorite: false,
    gender: 'unisex',
    openingHours: '09:00 AM - 09:30 PM',
    phone: '+91 731 425 8890',
    amenities: ['AC Waiting Lounge', 'Complimentary Beverage', 'Free Wi-Fi', 'Card & UPI', 'Sanitized Tools'],
    stylists: [
      {
        id: 's1',
        name: 'Aarav Sharma',
        role: 'Master Hair Stylist',
        specialization: 'Fade Cuts, Texture & Layering',
        experience: '8+ years',
        rating: 4.9,
        reviewsCount: 380,
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
        workingHours: '09:00 AM - 08:30 PM',
        breaks: ['01:00 PM - 02:00 PM', '05:00 PM - 05:30 PM'],
        daysOff: ['Tuesday'],
        active: true,
        bookedSlots: {
          'Oct 24': ['10:00 AM', '11:00 AM', '03:30 PM', '06:00 PM'],
          'Oct 25': ['10:30 AM', '02:00 PM', '04:30 PM'],
          'Oct 26': ['11:00 AM', '01:00 PM', '05:00 PM'],
        },
      },
      {
        id: 's2',
        name: 'Sneha Verma',
        role: 'Senior Colorist & Stylist',
        specialization: 'Balayage, Keratin, O3+ Facials',
        experience: '6 years',
        rating: 4.8,
        reviewsCount: 290,
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
        workingHours: '10:00 AM - 09:00 PM',
        breaks: ['01:30 PM - 02:30 PM'],
        daysOff: ['Wednesday'],
        active: true,
        bookedSlots: {
          'Oct 24': ['11:30 AM', '02:30 PM', '04:00 PM'],
          'Oct 25': ['10:00 AM', '01:30 PM'],
          'Oct 26': ['12:30 PM', '03:30 PM'],
        },
      },
      {
        id: 's3',
        name: 'Vikram Mehta',
        role: 'Beard & Precision Barber',
        specialization: 'Beard Sculpting, Razor Fades & Head Spa',
        experience: '5 years',
        rating: 4.85,
        reviewsCount: 215,
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
        workingHours: '09:30 AM - 09:00 PM',
        breaks: ['02:00 PM - 03:00 PM'],
        daysOff: ['Monday'],
        active: true,
        bookedSlots: {
          'Oct 24': ['09:30 AM', '01:30 PM', '07:00 PM'], // 10:00 AM & 11:00 AM ARE FREE for Vikram!
          'Oct 25': ['11:00 AM', '03:00 PM'],
          'Oct 26': ['10:00 AM', '02:00 PM'],
        },
      },
      {
        id: 's4',
        name: 'Priya Patel',
        role: 'Skin & Bridal Specialist',
        specialization: 'Hydra Facials, Organic Waxing & Makeup',
        experience: '7 years',
        rating: 4.92,
        reviewsCount: 310,
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
        workingHours: '10:00 AM - 08:00 PM',
        breaks: ['01:00 PM - 02:00 PM'],
        daysOff: ['Thursday'],
        active: true,
        bookedSlots: {
          'Oct 24': ['10:30 AM', '12:30 PM', '04:30 PM'],
          'Oct 25': ['11:30 AM', '03:30 PM'],
          'Oct 26': ['01:30 PM', '05:30 PM'],
        },
      },
    ],
    services: [
      { id: 'ls-1', name: 'Signature Haircut & Wash', category: 'haircut', duration: '40 mins', price: 349, originalPrice: 499, popular: true },
      { id: 'ls-2', name: 'Beard Sculpting & Hot Towel', category: 'beard', duration: '25 mins', price: 199, originalPrice: 250, popular: true },
      { id: 'ls-3', name: 'Deep Cleansing Charcoal Facial', category: 'facial', duration: '50 mins', price: 799, originalPrice: 1200 },
      { id: 'ls-4', name: 'L’Oréal Global Hair Color', category: 'hair-color', duration: '90 mins', price: 1499, originalPrice: 1999 },
    ],
  },
  {
    id: 'style-studio',
    name: 'Style Studio',
    rating: 4.6,
    reviewsCount: 850,
    distance: '1.2 km away',
    address: '5th Floor, Treasure Island Mall, Palasia',
    city: 'Indore',
    lat: 22.7244,
    lng: 75.8839,
    image: 'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1622288432450-277d0fef5ed6?auto=format&fit=crop&w=800&q=80',
    ],
    startingPrice: 399,
    isFavorite: false,
    gender: 'unisex',
    openingHours: '10:00 AM - 10:00 PM',
    phone: '+91 731 408 1122',
    amenities: ['Mall Parking', 'AC', 'Coffee Bar', 'Luxury Wash Station', 'Digital Payments'],
    stylists: [
      { id: 's3', name: 'Vikram Singh', role: 'Creative Director', rating: 4.9, avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80' },
      { id: 's4', name: 'Pooja Kulkarni', role: 'Skin Specialist', rating: 4.7, avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80' },
    ],
    services: [
      { id: 'ss-1', name: 'Advanced Layer Haircut + Blowdry', category: 'haircut', duration: '45 mins', price: 499, originalPrice: 700, popular: true },
      { id: 'ss-2', name: 'O3+ Brightening Glow Facial', category: 'facial', duration: '60 mins', price: 1199, originalPrice: 1599, popular: true },
      { id: 'ss-3', name: 'Keratin Hair Spa & Mask', category: 'spa', duration: '60 mins', price: 999, originalPrice: 1400 },
    ],
  },
  {
    id: 'the-hair-craft',
    name: 'The Hair Craft',
    rating: 4.8,
    reviewsCount: 2130,
    distance: '1.5 km away',
    address: 'Near C21 Mall, Scheme 54',
    city: 'Indore',
    lat: 22.7480,
    lng: 75.8975,
    image: 'https://images.unsplash.com/photo-1582095133179-bfd08e2fc6b3?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1582095133179-bfd08e2fc6b3?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80',
    ],
    startingPrice: 449,
    isFavorite: false,
    gender: 'unisex',
    openingHours: '09:30 AM - 09:00 PM',
    phone: '+91 731 498 7765',
    amenities: ['Premium Organic Products', 'Air Purified', 'Private Grooming Pods', 'Espresso Lounge'],
    stylists: [
      { id: 's5', name: 'Rohan Mehta', role: 'Senior Stylist & Barber', rating: 4.9, avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80' },
      { id: 's6', name: 'Ananya Roy', role: 'Hair Care Consultant', rating: 4.8, avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80' },
    ],
    services: [
      { id: 'thc-1', name: 'Executive Grooming Package', category: 'haircut', duration: '75 mins', price: 799, originalPrice: 1100, popular: true },
      { id: 'thc-2', name: 'Beard Trimming & Conditioning', category: 'beard', duration: '30 mins', price: 249, originalPrice: 350 },
      { id: 'thc-3', name: 'Highlights & Ombre Streaks', category: 'hair-color', duration: '120 mins', price: 1899, originalPrice: 2500, popular: true },
    ],
  },
  {
    id: 'glamour-beauty',
    name: 'Glamour Beauty',
    rating: 4.5,
    reviewsCount: 620,
    distance: '2.1 km away',
    address: 'Opposite High Court, South Tukoganj',
    city: 'Indore',
    lat: 22.7165,
    lng: 75.8770,
    image: 'https://images.unsplash.com/photo-1629731602701-44aa0a202758?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1629731602701-44aa0a202758?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=800&q=80',
    ],
    startingPrice: 350,
    isFavorite: false,
    gender: 'unisex',
    openingHours: '10:00 AM - 08:30 PM',
    phone: '+91 731 254 3300',
    amenities: ['Dedicated Women Section', 'Hygienic Waxing Suites', 'Organic Herbal Teas'],
    stylists: [
      { id: 's7', name: 'Meera Deshmukh', role: 'Bridal Artistry Lead', rating: 4.8, avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80' },
    ],
    services: [
      { id: 'gb-1', name: 'Rica Full Arms + Legs Waxing', category: 'waxing', duration: '45 mins', price: 699, originalPrice: 999, popular: true },
      { id: 'gb-2', name: 'Hydra Dew Moisture Facial', category: 'facial', duration: '60 mins', price: 1299, originalPrice: 1800, popular: true },
      { id: 'gb-3', name: 'Deluxe Pedicure & Foot Spa', category: 'more', duration: '50 mins', price: 499, originalPrice: 750 },
    ],
  },
  {
    id: 'envi-salon',
    name: 'Envi Salon & Spa',
    rating: 4.9,
    reviewsCount: 3420,
    distance: '2.8 km away',
    address: 'Phoenix Citadel Mall, MR 10 Road',
    city: 'Indore',
    lat: 22.7712,
    lng: 75.9180,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=800&q=80',
    ],
    startingPrice: 599,
    isFavorite: false,
    gender: 'unisex',
    openingHours: '10:30 AM - 10:00 PM',
    phone: '+91 731 668 9000',
    amenities: ['VIP Rooms', 'Steam & Sauna', 'Beverage Menu', 'Valet Parking'],
    stylists: [
      { id: 's8', name: 'Zoya Khan', role: 'Celebrity Stylist', rating: 5.0, avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80' },
    ],
    services: [
      { id: 'es-1', name: 'Botox Hair Treatment', category: 'hair-color', duration: '120 mins', price: 3499, originalPrice: 4500, popular: true },
      { id: 'es-2', name: 'Deep Tissue Aromatherapy Spa', category: 'spa', duration: '60 mins', price: 1799, originalPrice: 2400 },
    ],
  },
];

export const SPECIAL_OFFERS = [
  {
    id: 'off-1',
    title: 'Special Offers For You!',
    subtitle: 'Grab exciting deals and discounts on your favorite services.',
    discount: '40% OFF',
    code: 'AAORA40',
    expiry: 'Valid till 31 Aug',
    badge: 'Trending Deal',
    bgColor: 'bg-blue-600',
    textColor: 'text-blue-600',
  },
  {
    id: 'off-2',
    title: 'First Booking Flat ₹200 OFF',
    subtitle: 'Applicable on any salon service with min order value ₹500.',
    discount: 'FLAT ₹200',
    code: 'WELCOME200',
    expiry: 'Valid for new users',
    badge: 'First Time User',
    bgColor: 'bg-indigo-600',
    textColor: 'text-indigo-600',
  },
  {
    id: 'off-3',
    title: 'Men Grooming Supreme Combo',
    subtitle: 'Haircut + Beard Styling + Head Massage at special price.',
    discount: '30% OFF',
    code: 'MENLOOKS',
    expiry: 'Valid this weekend',
    badge: 'Men Special',
    bgColor: 'bg-cyan-700',
    textColor: 'text-cyan-700',
  },
  {
    id: 'off-4',
    title: 'Bridal & Party Glow Festival',
    subtitle: 'O3+ Facial + Hair Spa + Rica Waxing package discount.',
    discount: '50% OFF',
    code: 'GLOW50',
    expiry: 'Limited slots daily',
    badge: 'Women Exclusive',
    bgColor: 'bg-pink-600',
    textColor: 'text-pink-600',
  },
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif-1',
    title: '🎉 Flat 40% OFF Weekend Bonanza',
    message: 'Book any Haircut or Facial this weekend at top rated salons in Indore and save big with code AAORA40.',
    time: '10 mins ago',
    unread: true,
  },
  {
    id: 'notif-2',
    title: '⭐ Looks Salon has new available slots',
    message: 'Senior stylist Aarav is accepting bookings for today evening.',
    time: '2 hours ago',
    unread: true,
  },
  {
    id: 'notif-3',
    title: '✨ Welcome to AAORA!',
    message: 'Explore verified salons near you with guaranteed hygiene and best pricing.',
    time: '1 day ago',
    unread: false,
  },
];

export const STYLE_TRENDS = [
  {
    id: 'style-1',
    name: 'Mid Taper Fade & Textured Crop',
    gender: 'men',
    category: 'Haircut',
    faceShape: ['Oval', 'Square', 'Heart'],
    hairType: ['Straight', 'Wavy'],
    difficulty: 'Low Maintenance',
    duration: '40 mins',
    price: 349,
    description: 'Clean mid-fade with scissor-cut textured crop on top. Great modern versatility.',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    tags: ['Trending', 'Modern', 'Low-Maintenance'],
    recommendedSalonId: 'looks-salon',
    recommendedBarber: 'Aarav Sharma',
  },
  {
    id: 'style-2',
    name: 'Executive Pompadour & Tapered Beard',
    gender: 'men',
    category: 'Hair & Beard',
    faceShape: ['Round', 'Oval', 'Diamond'],
    hairType: ['Straight', 'Thick'],
    difficulty: 'Medium Maintenance',
    duration: '60 mins',
    price: 499,
    description: 'High-volume swept back crown paired with sharp razor-line geometric beard.',
    image: 'https://images.unsplash.com/photo-1622288432450-277d0fef5ed6?auto=format&fit=crop&w=600&q=80',
    tags: ['Formal', 'Classic', 'Sharp'],
    recommendedSalonId: 'the-hair-craft',
    recommendedBarber: 'Rohan Mehta',
  },
  {
    id: 'style-3',
    name: 'Butterfly Layers & Curtain Bangs',
    gender: 'women',
    category: 'Hair Styling',
    faceShape: ['Oval', 'Heart', 'Square', 'Round'],
    hairType: ['Wavy', 'Straight', 'Fine'],
    difficulty: 'Easy Daily Styling',
    duration: '50 mins',
    price: 649,
    description: 'Feathered face-framing cascading butterfly layers with bouncy blowdry volume.',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    tags: ['Viral Trend', 'High Volume', 'Face-Framing'],
    recommendedSalonId: 'looks-salon',
    recommendedBarber: 'Sneha Verma',
  },
  {
    id: 'style-4',
    name: 'Sun-Kissed Caramel Balayage',
    gender: 'women',
    category: 'Hair Color',
    faceShape: ['All Face Shapes'],
    hairType: ['Medium to Long'],
    difficulty: 'Premium Glow',
    duration: '120 mins',
    price: 1899,
    description: 'Hand-painted honey caramel tones blending seamlessly into natural dark roots.',
    image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=600&q=80',
    tags: ['Luxury', 'Dimensional', 'Long-Lasting'],
    recommendedSalonId: 'style-studio',
    recommendedBarber: 'Pooja Kulkarni',
  },
  {
    id: 'style-5',
    name: 'French Crop with Sharp Low Fade',
    gender: 'men',
    category: 'Haircut',
    faceShape: ['Square', 'Oval'],
    hairType: ['Short', 'Curly', 'Straight'],
    difficulty: 'Ultra Low Maintenance',
    duration: '35 mins',
    price: 299,
    description: 'Short blunt fringe with gradient skin fade on sides. Sharp athletic look.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    tags: ['Athletic', 'Clean', 'Fade'],
    recommendedSalonId: 'looks-salon',
    recommendedBarber: 'Vikram Mehta',
  },
  {
    id: 'style-6',
    name: 'Glossy Glass Hair & Keratin Infusion',
    gender: 'women',
    category: 'Hair Care & Spa',
    faceShape: ['All Face Shapes'],
    hairType: ['Frizzy', 'Dry', 'Straight', 'Wavy'],
    difficulty: 'Mirror Finish',
    duration: '90 mins',
    price: 1499,
    description: 'Ultra-reflective silky keratin gloss treatment for mirror-smooth shine.',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
    tags: ['Mirror Shine', 'Frizz Free', 'Spa'],
    recommendedSalonId: 'envi-salon',
    recommendedBarber: 'Zoya Khan',
  },
];

export const OFFERS_DATA = SPECIAL_OFFERS;
export const STYLE_LOOKS = STYLE_TRENDS;

export const INITIAL_BOOKINGS_DATA = [
  {
    id: 'BK-892140',
    salonId: 'looks-salon',
    salonName: 'Looks Salon',
    salonAddress: 'Plot 14, Ring Road, Vijay Nagar, Indore',
    salonImage: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=800&q=80',
    salonPhone: '+91 731 425 8890',
    serviceName: 'Signature Haircut & Wash',
    services: [
      { name: 'Signature Haircut & Wash', price: 349, duration: '40 mins' },
      { name: 'Beard Sculpting & Hot Towel', price: 199, duration: '25 mins' },
    ],
    totalDuration: '65 mins',
    price: 548,
    discount: 55,
    tax: 25,
    totalAmount: 518,
    paymentMethod: 'Razorpay Online',
    paymentStatus: 'Paid Full',
    advancePaid: 518,
    remainingAmount: 0,
    transactionId: 'pay_rzp_98a76b5c4d3e',
    date: 'Tomorrow, Oct 25',
    rawDate: '2026-10-25',
    time: '11:00 AM',
    endTime: '12:05 PM',
    stylist: 'Aarav Sharma (Master Stylist)',
    stylistAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    status: 'Confirmed', // 'Pending' | 'Confirmed' | 'Customer Arrived' | 'In Progress' | 'Completed' | 'Cancelled' | 'No Show'
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=BK-892140-LOOKS-AARAV',
    customerName: 'Ajeet Lodhi',
    customerPhone: '+91 98765 43210',
    customerEmail: 'ajeetlodhii01@gmail.com',
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    isReviewed: false,
    remindersEnabled: true,
  },
  {
    id: 'BK-774912',
    salonId: 'the-hair-craft',
    salonName: 'The Hair Craft',
    salonAddress: 'Near C21 Mall, Scheme 54, Indore',
    salonImage: 'https://images.unsplash.com/photo-1582095133179-bfd08e2fc6b3?auto=format&fit=crop&w=800&q=80',
    salonPhone: '+91 731 498 7765',
    serviceName: 'Executive Grooming Package',
    services: [
      { name: 'Executive Grooming Package', price: 799, duration: '75 mins' },
    ],
    totalDuration: '75 mins',
    price: 799,
    discount: 100,
    tax: 35,
    totalAmount: 734,
    paymentMethod: 'Pay at Salon',
    paymentStatus: 'Pending at Venue',
    advancePaid: 0,
    remainingAmount: 734,
    transactionId: 'pay_at_salon_7749',
    date: 'Saturday, Oct 26',
    rawDate: '2026-10-26',
    time: '04:30 PM',
    endTime: '05:45 PM',
    stylist: 'Rohan Mehta (Senior Stylist)',
    stylistAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
    status: 'Pending',
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=BK-774912-HAIRCRAFT-ROHAN',
    customerName: 'Ajeet Lodhi',
    customerPhone: '+91 98765 43210',
    customerEmail: 'ajeetlodhii01@gmail.com',
    createdAt: new Date(Date.now() - 3600000 * 20).toISOString(),
    isReviewed: false,
    remindersEnabled: true,
  },
  {
    id: 'BK-552109',
    salonId: 'style-studio',
    salonName: 'Style Studio',
    salonAddress: '5th Floor, Treasure Island Mall, Palasia, Indore',
    salonImage: 'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=800&q=80',
    salonPhone: '+91 731 408 1122',
    serviceName: 'O3+ Brightening Glow Facial',
    services: [
      { name: 'O3+ Brightening Glow Facial', price: 1199, duration: '60 mins' },
    ],
    totalDuration: '60 mins',
    price: 1199,
    discount: 250,
    tax: 48,
    totalAmount: 997,
    paymentMethod: 'Advance 25% (UPI)',
    paymentStatus: 'Advance Paid',
    advancePaid: 250,
    remainingAmount: 747,
    transactionId: 'pay_adv_552109',
    date: 'Oct 18, 2026',
    rawDate: '2026-10-18',
    time: '02:00 PM',
    endTime: '03:00 PM',
    stylist: 'Pooja Kulkarni (Skin Specialist)',
    stylistAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    status: 'Completed',
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=BK-552109-STYLESTUDIO',
    customerName: 'Ajeet Lodhi',
    customerPhone: '+91 98765 43210',
    customerEmail: 'ajeetlodhii01@gmail.com',
    createdAt: new Date(Date.now() - 3600000 * 180).toISOString(),
    isReviewed: true,
    userRating: 5,
    userReview: 'Amazing brightening facial! Skin felt very fresh and radiant. Pooja is very professional.',
    remindersEnabled: false,
  },
];

